name: Update Chess Rating in README
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
on:
  schedule:
   - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Update README with Chess Stats
        run: |
          USERNAME="krix0s"
          URL="https://www.chess.com/callback/member/stats/$USERNAME"
          DATA=$(curl -s $URL)

          CURRENT_RATING=$(echo $DATA | jq '[.stats[].stats.rating] | max')

          OLD_CURRENT_RATING=$(grep -oP '(?<=📈 Current rating: )\d+' README.md)
          OLD_MAX_RATING=$(grep -oP '(?<=🏆 Max rating: )\d+' README.md)
  
          OLD_CURRENT_RATING=${OLD_CURRENT_RATING:-0}
          OLD_MAX_RATING=${OLD_MAX_RATING:-0}

          if [ "$CURRENT_RATING" -gt "$OLD_MAX_RATING" ]; then
            MAX_RATING=$CURRENT_RATING
          else
            MAX_RATING=$OLD_MAX_RATING
          fi

          DATE=$(date +"%Y-%m-%d %H:%M:%S UTC")

          # Update Chess Stats section.
          awk -v current="$CURRENT_RATING" -v max="$MAX_RATING" '
            BEGIN {inside=0}
            /<!-- CHESS_STATS_START -->/ {inside=1; print; print "      - 📈 Current rating: " current; print "      - 🏆 Max rating: " max; next}
            /<!-- CHESS_STATS_END -->/ {inside=0}
            !inside {print}
          ' README.md > temp.md && mv temp.md README.md

          # Update last updated timestamp at the end of the README.
          awk -v date="$DATE" '
            {if (!found && /<!-- LAST_UPDATE -->/) {print "📅 *Last update:* " date " <!-- LAST_UPDATE -->"; found=1; next} }
            !/<!-- LAST_UPDATE -->/ {print}
          ' README.md > temp.md && mv temp.md README.md

      - name: Configure Git
        run: |
          git config --local user.name "CristianPeralta"
          git config --local user.email "cbperaltasegura@gmail.com"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/CristianPeralta/CristianPeralta.git

      - name: Commit and push
        run: |
          git add README.md
          git commit -m "Automatic update: $CURRENT_RATING / $MAX_RATING"
          git push
